server:
  port: ${PORT:8080}
#  port: 8080

spring:
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/application?allowPublicKeyRetrieval=true&serverTimezone=Europe/Moscow&useSSL=false&useLegacyDatetimeCode=false}
#    url: jdbc:mysql://localhost:3306/application?allowPublicKeyRetrieval=true&serverTimezone=Europe/Moscow&useSSL=false&useLegacyDatetimeCode=false
    useJDBCCompliantTimeZoneShift: true
    username: root
    password: KiGa9879874!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
            time_zone: Europe/Moscow
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
#  flyway:
#    enabled: true
#    locations:
#      classpath: db/migration,db/migration/{vendor}
  mail:
    host: smtp.gmail.com
    port: 587
    username: "application.skillbox@gmail.com"
    password: "KiGa9879874!"
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

blog:
  title: "DevPub"
  subtitle: "Рассказы разработчиков"
  phone: "+7 903 666-44-55"
  email: "mail@mail.ru"
  copyright: "Дмитрий Сергеев"
  copyright_from: "2005"

post:
  announce:
    max_length: 150
  title:
    min_length: 3
  text:
    min_length: 50
  image:
    upload_dir: src/main/resources/upload
    format: jpg

captcha:
  secret_code_length: 22
  timeout: 1 # hour
  image:
    title: data:image/png;base64
    format: jpg
    width: 100
    height: 35
    text:
      length: 5

user:
  password:
    restore:
      code:
        length: 45
      message:
        from: application.skillbox
        subject: "Ссылка для восстановления пароля"
        link: "/login/change-password/"
        server_link: "http://localhost:"
    length: 6
  image:
    avatar_dir: src/main/resources/avatars
    format: jpg
    max_size: 10000000 # bytes (10Mb)

image:
  folder_length: 6
  name_length: 5

post_comment:
  min_length: 3

