server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/application?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    useJDBCCompliantTimeZoneShift: true
    username: root
    password: KiGa9879874!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations:
      classpath: db/migration,db/migration/{vendor}

blog:
  title: "DevPub"
  subtitle: "Рассказы разработчиков"
  phone: "+7 903 666-44-55"
  email: "mail@mail.ru"
  copyright: "Дмитрий Сергеев"
  copyright_from: "2005"

post:
  announce:
    max_length: 150
  title:
    min_length: 3
  text:
    min_length: 50

captcha:
  secret_code_length: 22
  timeout: 1 # hour
  image:
    title: data:image/png;base64
    format: png
    width: 100
    height: 35
    text:
      length: 5

user:
  password:
    length: 6

image:
  root_dir: upload
  format: jpg
  max_size: 10000000 #bytes = 10Mb

post_comment:
  min_length: 3

