server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/application?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    useJDBCCompliantTimeZoneShift: true
    username: root
    password: KiGa9879874!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          dialect: org.hibernate.dialect.MySQL8Dialect
