insert into tags(name) values('Theory of computation');
insert into tags(name) values('Computer science');
insert into tags(name) values('Programming');
insert into tags(name) values('Mathematic&Algebra');
insert into tags(name) values('Sexism');
insert into tags(name) values('Java');
insert into tags(name) values('CS2');
insert into tags(name) values('Career guidance');
insert into tags(name) values('Python');
insert into tags(name) values('Go');
insert into tags(name) values('C');
insert into tags(name) values('Cryptocurrency');
insert into tags(name) values('Evolution theory');
insert into tags(name) values('Psychology');
insert into tags(name) values('K-12');
insert into tags(name) values('Software development');
insert into tags(name) values('Pedagogy');
insert into tags(name) values('CSS');
insert into tags(name) values('Sass');
insert into tags(name) values('iOS&Android');
insert into tags(name) values('Algorithms');
insert into tags(name) values('Culture');
insert into tags(name) values('Game development');
insert into tags(name) values('Business');
